# Generated by Django 4.2.28 on 2026-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='jamb_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['programme', 'level'], name='students_program_130da0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'admission_year'], name='students_status_a4d0f4_idx'),
        ),
    ]
