# Generated by Django 6.0.2 on 2026-02-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NUCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('statistical', 'Statistical Digest'), ('compliance', 'Compliance Report'), ('accreditation', 'Accreditation Report'), ('annual', 'Annual Report')], max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='nuc_reports/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nuc_reports',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_status', models.CharField(choices=[('pending', 'Pending'), ('accredited', 'Accredited'), ('probation', 'Probation'), ('denied', 'Denied')], max_length=20)),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('nuc_ref_number', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='students.programme')),
            ],
            options={
                'db_table': 'accreditations',
                'ordering': ['-accreditation_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nuc.compliancechecklist')),
            ],
            options={
                'db_table': 'compliance_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GraduationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('total_graduands', models.PositiveIntegerField(default=0)),
                ('first_class', models.PositiveIntegerField(default=0)),
                ('second_class_upper', models.PositiveIntegerField(default=0)),
                ('second_class_lower', models.PositiveIntegerField(default=0)),
                ('third_class', models.PositiveIntegerField(default=0)),
                ('pass_class', models.PositiveIntegerField(default=0)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('nuc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='students.programme')),
            ],
            options={
                'db_table': 'graduation_lists',
                'ordering': ['-session'],
            },
        ),
    ]
