# Generated by Django 6.0.2 on 2026-02-18 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_registration_open', models.BooleanField(default=False)),
                ('is_exam_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('credit_units', models.PositiveIntegerField(default=3)),
                ('level', models.CharField(max_length=10)),
                ('semester', models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('rain', 'Rain Semester'), ('harmattan', 'Harmattan Semester')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.programme')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
                'unique_together': {('programme', 'code', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('rain', 'Rain Semester'), ('harmattan', 'Harmattan Semester')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('exam_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicsession')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['session', 'name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_absent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sittings', to='students.student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'db_table': 'exam_sittings',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.FloatField(blank=True, null=True)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (70-100)'), ('B', 'B (60-69)'), ('C', 'C (50-59)'), ('D', 'D (45-49)'), ('E', 'E (40-44)'), ('F', 'F (0-39)')], max_length=2)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.course')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'db_table': 'results',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='registered', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='students.student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'db_table': 'course_registrations',
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_courses', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'db_table': 'course_allocations',
                'unique_together': {('course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveIntegerField(default=0)),
                ('attended_classes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'db_table': 'attendances',
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
