# Generated by Django 4.2.28 on 2026-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'course', 'semester'], name='attendances_student_7d2b91_idx'),
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['semester', 'status'], name='course_regi_semeste_de77de_idx'),
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['student', 'semester'], name='course_regi_student_7e5951_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'semester'], name='results_student_c7481a_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['course', 'semester'], name='results_course__970f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['is_published'], name='results_is_publ_99e7b2_idx'),
        ),
    ]
